### ISSUE TITLE
replacing stop duration where "1" or "2"

### ISSUE THREAD

**Issue by pirsquared** [justmarkham/pycon-2018-tutorial#1]
A very pandas-esque way to replace the `"1"` or `"2"` with `np.nan` is to use the [`pandas.Series.mask`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.mask.html) method.

```
ri.stop_duration.mask(ri.stop_duration.isin(['1', '2']), inplace=True)
ri.stop_duration.value_counts(dropna=False)

0-15 Min     69543
16-30 Min    13635
NaN           5335
30+ Min       3228
Name: stop_duration, dtype: int64
```

**Comment by justmarkham** [comment]
@pirsquared Neat! Thanks for sharing!
