### ISSUE TITLE
Clever way to calculate if most stops occur at night

### ISSUE THREAD

**Issue by pirsquared** [justmarkham/pycon-2018-tutorial#2]
Define night to be between 10 pm to 4 am.  
Idea: shift the hour by 2 (add 2 to the hour) producing hours that range from 2 to 25.  Then modulo 24 to have shifted the hours by 2.

```
ri.stop_datetime.dt.hour.add(2).mod(24).lt(6).mean()

0.24974656914574728
```

**Comment by justmarkham** [comment]
@pirsquared Interesting! Though a bit hard to mentally parse for me.
